[package]
name = "tagflow-rust-pyo3"
version = "0.1.0"
edition = "2021"

[lib]
name = "_tagflow_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
html-escape = "0.2"
regex = "1.0"
once_cell = "1.19"