openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
  description: Example API for testing openapi-python-types

paths:
  /users:
    get:
      summary: List all users
      operationId: listUsers
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
          required: false
        - name: offset
          in: query
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  
  /users/{userId}:
    get:
      summary: Get a user by ID
      operationId: getUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    
    put:
      summary: Update a user
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    
    delete:
      summary: Delete a user
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: User deleted

components:
  schemas:
    User:
      type: object
      description: A user in the system
      required:
        - id
        - username
        - email
      properties:
        id:
          type: integer
          description: User ID
        username:
          type: string
          description: Username
        email:
          type: string
          description: Email address
        full_name:
          type: string
          description: Full name
        is_active:
          type: boolean
          description: Whether the user is active
        role:
          $ref: '#/components/schemas/UserRole'
    
    UserCreate:
      type: object
      description: Schema for creating a new user
      required:
        - username
        - email
      properties:
        username:
          type: string
        email:
          type: string
        full_name:
          type: string
        role:
          $ref: '#/components/schemas/UserRole'
    
    UserUpdate:
      type: object
      description: Schema for updating a user
      properties:
        username:
          type: string
        email:
          type: string
        full_name:
          type: string
        is_active:
          type: boolean
        role:
          $ref: '#/components/schemas/UserRole'
    
    UserRole:
      type: string
      description: User role
      enum:
        - admin
        - user
        - guest
